ALTER ROLE [db_owner] ADD MEMBER [PUNK-PC\Punk];


GO
ALTER ROLE [db_owner] ADD MEMBER [NT SERVICE\SQLSERVERAGENT];


GO
ALTER ROLE [db_owner] ADD MEMBER [NT Service\MSSQLSERVER];


GO
ALTER ROLE [db_owner] ADD MEMBER [NT AUTHORITY\NETWORK SERVICE];

